server:
  port: 9002

spring:
  cloud:
    config:
      import-check:
        enabled: false
  application:
    name: deposit-service

  data:
    mongodb:
      database: deposit-service
      host: localhost
      username: admin
      password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  #instance:
  #  instance-id: ${spring.application.name}:${random.uuid}
